"""NLLB-200-distilled-600M with phrase-level constrained beam search (exp/glossary-phrase-constrained).

Method: HF native `force_words_ids` with `PhrasalConstraint` + beam search (num_beams=4).
- Forces the term phrase to appear exactly once, at a position chosen by beam search.
- Surrounding tokens (including Korean particles/조사) generated naturally by the LM.
- Cap: at most 1 glossary term forced per sentence (the single most salient triggered term).
  Rationale: R3-3 found multi-term logit-bias front-loads terms out of order. Capping at
  1 term avoids multi-term interaction while still measuring term-recall on the slice.
- Release: once the term's tokens are emitted, the LM picks the particle freely.

This is Method 2 + Method 3 from the approach spec.

A-priori justification:
  R3-3's failure was perpetual per-token logit-boosting without position awareness.
  PhrasalConstraint uses beam search to find a beam path where the term appears,
  but does NOT boost individual term tokens at every step — it only enforces the
  phrase ONCE in the output, and the surrounding context is generated by the LM.
  This is the textbook fix (Hokamp & Liu 2017, Post & Vilar 2018).
  The cap-at-1 rule avoids the "term salad" failure mode from R3-3's multi-term runs.
"""
from __future__ import annotations

from typing import Dict, List, Optional, Tuple

import torch
from loguru import logger
from transformers import NllbTokenizer, AutoModelForSeq2SeqLM, PhrasalConstraint

# FLORES language code mapping
LANG_CODE_MAP = {
    "en": "eng_Latn",
    "ko": "kor_Hang",
    "eng_Latn": "eng_Latn",
    "kor_Hang": "kor_Hang",
}


class NllbPhraseConstrainedTranslator:
    """NLLB HF translator using PhrasalConstraint (force_words_ids) with beam search.

    Treatment: forces the single most-salient glossary term to appear in the output.
    Control: no constraint, greedy decoding (same as R3-3 control).
    """

    MODEL_ID = "facebook/nllb-200-distilled-600M"

    def __init__(
        self,
        glossary_entries: List[Dict],
        use_constraint: bool = True,
        num_beams: int = 4,
        max_new_tokens: int = 128,
        cap_terms: int = 1,
    ) -> None:
        """
        Args:
            glossary_entries: list of {src, tgt, dnt} dicts.
            use_constraint: if True, use PhrasalConstraint beam search (treatment).
                           if False, use greedy decoding (control).
            num_beams: number of beams for constrained beam search (>=4 for constraints).
            max_new_tokens: max output tokens.
            cap_terms: max number of terms to constrain per sentence (default 1).
        """
        self.glossary_entries = glossary_entries
        self.use_constraint = use_constraint
        self.num_beams = num_beams
        self.max_new_tokens = max_new_tokens
        self.cap_terms = cap_terms

        logger.info(f"Loading NLLB tokenizer from {self.MODEL_ID}")
        self.tokenizer = NllbTokenizer.from_pretrained(self.MODEL_ID)
        # NOTE: src_lang must be set as an attribute on NllbTokenizer, NOT passed
        # as a kwarg to __call__. In transformers 4.27.4, passing src_lang= to
        # __call__ generates "Keyword arguments not recognized" warning and does
        # NOT set the language prefix token. Setting the attribute before calling
        # is the correct API for this version.

        logger.info(f"Loading NLLB model from {self.MODEL_ID}")
        self.model = AutoModelForSeq2SeqLM.from_pretrained(
            self.MODEL_ID, torch_dtype=torch.float32
        )
        self.model.eval()
        logger.info(
            f"Model loaded. use_constraint={use_constraint}, "
            f"num_beams={num_beams}, cap_terms={cap_terms}"
        )

    def _get_triggered_entries(self, src_text: str, src_lang: str) -> List[Dict]:
        """Find glossary entries whose source term appears in src_text."""
        triggered = []
        src_lower = src_text.lower()
        for entry in self.glossary_entries:
            if src_lang in ("en", "eng_Latn"):
                term = entry.get("src", "")
            else:
                term = entry.get("tgt", "")
            if term and term.lower() in src_lower:
                triggered.append(entry)
        return triggered

    def _select_terms_to_force(
        self, triggered: List[Dict], tgt_lang: str
    ) -> List[Dict]:
        """Select up to cap_terms entries to actually constrain.

        Strategy: pick the longest source term (most specific) to avoid
        generic term collisions. Skip DNT entries (they should pass-through).
        """
        # Filter out DNT entries
        candidates = [e for e in triggered if not e.get("dnt", False)]
        if not candidates:
            return []

        # Sort by source term length descending (longest = most specific)
        if tgt_lang in ("ko", "kor_Hang"):
            candidates.sort(key=lambda e: len(e.get("src", "")), reverse=True)
        else:
            candidates.sort(key=lambda e: len(e.get("tgt", "")), reverse=True)

        return candidates[: self.cap_terms]

    def _build_constraints(
        self, selected: List[Dict], tgt_lang: str
    ) -> List[PhrasalConstraint]:
        """Build PhrasalConstraint objects from selected glossary entries."""
        constraints = []
        for entry in selected:
            if tgt_lang in ("ko", "kor_Hang"):
                tgt_text = entry.get("tgt", "")
            else:
                # ko->en direction: force English src term
                tgt_text = entry.get("src", "")

            if not tgt_text:
                continue

            # Encode without special tokens
            token_ids = self.tokenizer.encode(tgt_text, add_special_tokens=False)
            if not token_ids:
                logger.warning(f"Term '{tgt_text}' encodes to empty token list, skipping")
                continue

            logger.debug(f"  Constraining term: '{tgt_text}' -> token_ids={token_ids}")
            constraints.append(PhrasalConstraint(token_ids))

        return constraints

    def translate(
        self, src_text: str, src_lang: str = "en", tgt_lang: str = "ko"
    ) -> Tuple[str, List[Dict]]:
        """Translate a single sentence. Returns (translated_text, triggered_entries)."""
        src_flores = LANG_CODE_MAP.get(src_lang, src_lang)
        tgt_flores = LANG_CODE_MAP.get(tgt_lang, tgt_lang)

        triggered = self._get_triggered_entries(src_text, src_lang)

        # Tokenize — set src_lang as attribute (not kwarg, see __init__ note)
        self.tokenizer.src_lang = src_flores
        inputs = self.tokenizer(src_text, return_tensors="pt")
        forced_bos = self.tokenizer.convert_tokens_to_ids(tgt_flores)

        # Build constraints if treatment mode
        constraints = []
        selected_terms = []
        if self.use_constraint and triggered:
            selected_terms = self._select_terms_to_force(triggered, tgt_lang)
            if selected_terms:
                constraints = self._build_constraints(selected_terms, tgt_lang)

        with torch.no_grad():
            if constraints:
                # Constrained beam search: term phrase is FORCED to appear once.
                # The LM picks the position and surrounding tokens (incl. particles).
                # no_repeat_ngram_size=3 reduces (but does not eliminate) repetition
                # loops that can occur when beam search struggles to place the term.
                # length_penalty > 1 biases toward shorter sequences (earlier term
                # placement), reducing the garbage-then-term pattern.
                out = self.model.generate(
                    **inputs,
                    forced_bos_token_id=forced_bos,
                    max_new_tokens=self.max_new_tokens,
                    num_beams=self.num_beams,
                    constraints=constraints,
                    do_sample=False,
                    no_repeat_ngram_size=3,
                    length_penalty=1.5,
                )
            elif self.use_constraint:
                # Treatment mode but no triggered terms -> beam search without constraint
                # (still use beam search for consistency, just no constraint)
                out = self.model.generate(
                    **inputs,
                    forced_bos_token_id=forced_bos,
                    max_new_tokens=self.max_new_tokens,
                    num_beams=self.num_beams,
                    do_sample=False,
                )
            else:
                # Control: greedy decoding, no constraint, num_beams=1
                out = self.model.generate(
                    **inputs,
                    forced_bos_token_id=forced_bos,
                    max_new_tokens=self.max_new_tokens,
                    num_beams=1,
                    do_sample=False,
                )

        result = self.tokenizer.batch_decode(out, skip_special_tokens=True)[0]
        return result, triggered

    def translate_batch(
        self,
        sentences: List[str],
        src_lang: str = "en",
        tgt_lang: str = "ko",
    ) -> List[Tuple[str, List[Dict]]]:
        """Translate a list of sentences one by one."""
        results = []
        for i, sent in enumerate(sentences):
            hyp, triggered = self.translate(sent, src_lang=src_lang, tgt_lang=tgt_lang)
            results.append((hyp, triggered))
            if (i + 1) % 20 == 0:
                logger.info(f"  Translated {i+1}/{len(sentences)}")
        return results
